# Generated by Django 5.1.4 on 2025-01-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ratings',
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.TextField(default='No content', max_length=255),
        ),
    ]
